export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    SIGNUP: '/signup',
    ONBOARDING: '/onboarding',
    SELLER: {
        ACCOUNT: '/seller/account',
        DASHBOARD: '/seller/dashboard',
        INVENTORY: '/seller/inventory',
        NEW_INVENTORY: '/seller/new-inventory',
        ORDERS: '/seller/orders',
        ORDER_DETAILS: (id: string) => `/seller/orders/${id}`,
        SALES_ANALYTICS: '/seller/sales-analytics',
        STORE_SETTINGS: '/seller/store-settings',
        TRANSACTIONS: '/seller/transactions',
    },
    SUPER_ADMIN: {
        DASHBOARD: '/super-admin',
        STORES: '/super-admin/stores',
        STORE_DETAILS: (id: string) => `/super-admin/stores/${id}`,
        PRODUCTS: '/super-admin/products',
        PRODUCT_DETAILS: (id: string) => `/super-admin/products/${id}`,
        BUYERS: '/super-admin/buyers',
        BUYER_DETAILS: (id: string) => `/super-admin/buyers/${id}`,
        ORDERS: '/super-admin/orders',
        COMPLAINTS: '/super-admin/complaints',
        COMPLAINT_DETAILS: (id: string) => `/super-admin/complaints/${id}`,
        TRANSACTIONS: '/super-admin/transactions',
        SALES_ANALYTICS: '/super-admin/sales-analytics',
        ACCOUNT: '/super-admin/account',
    },
}